config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders

  get "/about" => "page#about"
  root 'page#index'
get "/location" => "page#location"

end

app/models/order.rb
class Order < ActiveRecord::Base
validates :First_Name, presence: true
validates :Last_Name, presence: true
validates :Location, presence: true
validates :Time, presence: true
validates :Cuisine, presence: true
validates :Email, presence: true
belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
   before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = current_user.orders.build
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.build(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

      def correct_user
      @order = current_user.orders.find_by(id: params[:id])
      redirect_to orders_path, notice: "Not authorized to edit this order" if @order.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:First_Name, :Last_Name, :Location, :Time, :Cuisine, :Email, :Additional_Comments)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def about
  end

  def location
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
def description_error
    if @order.errors[:First_Name].size > 0
      return "has-error"
    end
     if @order.errors[:Last_Name].size > 0
      return "has-error"
    end
     if @order.errors[:Location].size > 0
      return "has-error"
    end
     if @order.errors[:Time].size > 0
      return "has-error"
    end
     if @order.errors[:Cuisine].size > 0
      return "has-error"
    end
     if @order.errors[:Email].size > 0
      return "has-error"
    end

    return ""
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Bobcat Food Truck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<div class="navbar-wrapper" role="navigation">
  <div class="container-fluid">
    <div class="navbar navbar-inverse navbar-static-top">
     <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
        <a class="navbar-brand" href="/">The Bobcat Food Truck</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
           <li><%= link_to "Home", root_path %></li>
           <li><%= link_to "About", about_path %></li>
          <% if !user_signed_in? %>
          <li><%= link_to "Book Now", orders_path %></li>
            <% else %>
           <li><%= link_to "Book Now", new_order_path %></li>
            <% end %>
            <li><%= link_to "Find Now", location_path %></li>
             <% if user_signed_in? %>
        <li><%= link_to "Orders", orders_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %> 
          </ul>
        </div>
      </div>
    </div>
  </div><!-- /container -->
</div><!-- /navbar wrapper -->

</div><!-- /.container -->

<div class="container">
   <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
<%= yield %>
</div>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order, html: { class: "form-horizontal"} ) do |f| %>


<div class="jumbotron">
   <h1>Request the Truck</h1>
    <p><img class="img-responsive" src=" http://m1.behance.net/rendition/modules/86579007/disp/b3770565b3f468854f9f7fe706e3dd97.png"/> 
     </p>
  <% if @order.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button class="close" aria-hidden="true" data-dismiss="alert" type="button">&times;</button>

      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group <%= description_error %>">
   <%= f.label :First_Name, class: "control-label col-sm-2"%>
     <div class="col-sm-10"><p>
    <%= f.text_field :First_Name, class: "form-control" %>
  </p></div>
   <%= f.label :Last_Name, class: "control-label col-sm-2"%>
     <div class="col-sm-10"><p>
    <%= f.text_field :Last_Name, class: "form-control" %>
    </p></div>
    <%= f.label :Location, class: "control-label col-sm-2"%>
     <div class="col-sm-10"><p>
    <%= f.text_field :Location, class: "form-control" %>
  </p></div>
   <%= f.label :Time, class: "control-label col-sm-2"%>
     <div class="col-sm-10"><p>
    <%= f.text_field :Time, class: "form-control" %>
  </p></div>
   <%= f.label :Cuisine, class: "control-label col-sm-2"%>
     <div class="col-sm-10"><p>
    <%= f.text_field :Cuisine, class: "form-control" %>
  </p></div>
    <%= f.label :Email, class: "control-label col-sm-2"%>
     <div class="col-sm-10"><p>
    <%= f.text_field :Email, class: "form-control" %>
  </p></div>
    <%= f.label :Additional_Comments, class: "control-label col-sm-2"%>
     <div class="col-sm-10"><p>
    <%= f.text_field :Additional_Comments, class: "form-control" %>
 </p> </div>
  <div class="actions col-sm-offset-2"><p>
      <%= f.submit class: "btn btn-primary" %>
  </p>    
  </div>
   </div>
    </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
  <% if !user_signed_in? %>
<div class="jumbotron">
  <h1>To Request the Truck <b>please sign in!</b></h1>
 <p><img class="img-responsive" src=" http://m1.behance.net/rendition/modules/86579007/disp/b3770565b3f468854f9f7fe706e3dd97.png"/> 
     </p>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>
<% else %>

<h1>Listing Orders</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Location</th>
      <th>Time</th>
      <th>Cuisine</th>
      <th>Email</th>
      <th>Additional Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.First_Name %></td>
        <td><%= order.Last_Name %></td>
        <td><%= order.Location %></td>
        <td><%= order.Time %></td>
        <td><%= order.Cuisine %></td>
        <td><%= order.Email %></td>
        <td><%= order.Additional_Comments %></td>
          <% if current_user == order.user %>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Order', new_order_path, class: "btn btn-primary btn-lg" %>
<% end %>
<% end %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @order.First_Name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @order.Last_Name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @order.Location %>
</p>

<p>
  <strong>Time:</strong>
  <%= @order.Time %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @order.Cuisine %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.Email %>
</p>

<p>
  <strong>Additional Comments:</strong>
  <%= @order.Additional_Comments %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/page/about.html.erb
<div class="jumbotron">
<div class="page-header">
  <h1>About The Bobcat Food Truck</h1>
</div>

<div class="row">
  <div class="col-md-4"><img class="img-responsive" src="http://www.smallfoodbiz.com/wp-content/uploads/gabi_091410_foodtruck-m.jpg"/></div>
  <div class="col-md-8">
    <h2>What we do?</h2>

    <p>We provide a cusotmizable food experience for Bates Students through:</p>

    <ul>
      <li>Location Requests</li>
      <li>Time Requests</li>
      <li>Cuisine Requests</li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <h3>Additionally, we value Farm to Fork</h3>

    <p>We believe in supporting and building relationships with local Farms</p>

    <p>Here is a list of our partners and what they provide</p>

    <ul>
      <li>Vegetables and Fruits from Freedom Farm in Freedom </li>
      <li>Beef, Sausage and Bacon from Weebit Farm in Orland</li>
      <li>Chicken from Serendipity Acres in North Yarmouth</li>
      <li>Fish from Free Range Fish in Portland</li>
      <li>Eggs from Common Wealth Farm in Unity</li>
      <li>Bread from Forage Market in Lewiston</li>
    </ul>

    <p>We also get additional local foods through the Crown of Maine Organic Cooperative and Farm Fresh Connection.</p>
  </div>
  <div class="col-md-4"><img class="img-responsive" src="http://s3-media2.ak.yelpcdn.com/bphoto/NYgcwILUL1gwB-zsHYYiQQ/ls.jpg"/></div>
  <div class="col-md-4"><img class="img-responsive" src="http://www.localsproutscooperative.com/wp-content/uploads/freedomfarm.jpg"/></div>
</div>
</div>

app/views/page/index.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="http://www.willstrathmann.com/wp-content/uploads/2013/02/bates-alumni-web-opt.jpg" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Request the Truck</h1>
          <pthis is="" an="" example="" layout="" with="" carousel="" that="" uses="" the="" bootstrap="" 3="" styles.<="" small=""><p></p>
          <% if !user_signed_in? %>
            <p><a class="btn btn-lg btn-primary" 
            href="/orders">Book Now</a>
            <% else %>
            <p><a class="btn btn-lg btn-primary" 
            href="/orders/new">Book Now</a>
            <% end %>
        </p>
      </pthis>
      </div>
      </div>
    </div>
    <div class="item">
      <img src="http://media-cache-ec0.pinimg.com/originals/a0/7e/63/a07e635835d385b05a17d068fbc82946.jpg" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>We believe in Community Engagement</h1>
          <p><a class="btn btn-large btn-primary" href="/about">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="http://www.bates.edu/about/files/2009/06/648C24C25.jpg" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Find the Truck </h1>
          <p><a class="btn btn-large btn-primary" href="/location">Find Now</a></p>
        </div>
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>  
</div>
<!-- /.carousel -->

app/views/page/location.html.erb
<div class="jumbotron">
<h1>Current Location</h1>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2864.8721487480207!2d-70.20951899999997!3d44.10662999999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cb26bbec0584ebd%3A0x22a44f1ed7248ffc!2s10+Frye+St!5e0!3m2!1sen!2sus!4v1400097095864" width="600" height="450" frameborder="0" style="border:0"></iframe>

</div>